In [1]:
import numpy as np

In [6]:
myarr = np.array([2,4,57,756,4],np.int32)

In [9]:
myarr[2]=34

In [13]:
myarrlist = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [16]:
myarrlist.dtype

dtype('int64')

In [17]:
myarrlist.shape

(3, 3)

In [19]:
myarrlist.size

9

In [20]:
np.array({12,15,15})

array({12, 15}, dtype=object)

In [22]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
larr=np.linspace(1,5,5)

In [33]:
np.empty((4,6))

array([[ 4.65600638e-310,  0.00000000e+000,  6.91388941e-310,
         8.53448752e+234,  6.91389003e-310,  6.91388941e-310],
       [-1.89533954e+096,  6.91389070e-310,  6.91388941e-310,
         9.23043109e+282,  6.91388674e-310,  6.91388941e-310],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [35]:
np.empty_like(larr)

array([1., 2., 3., 4., 5.])

In [36]:
ide = np.identity(45)

In [37]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [39]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
x.sum(axis=1)

array([ 6, 15, 24])

In [51]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
for x in x.flat:
    print(x)

1
2
3
4
5
6
7
8
9


In [53]:
x.ndim

0

In [54]:
x.nbytes

8

In [61]:
one = np.array([2,3,44,65,6,8])

In [65]:
one.argmax()

5

In [64]:
one.argsort()

array([0, 1, 2, 3, 4, 5])