In [1]:
import itertools
# colors = ['red', 'orange', 'yellow', 'green', 'blue', 'violet']
# for color in itertools.cycle(colors):
#     print(color)

In [2]:
s = {1, 2, 3, 2, 3, 4}
# s = set([1, 2, 3])

In [3]:
s

{1, 2, 3, 4}

In [4]:
s.add(5)
s

{1, 2, 3, 4, 5}

In [5]:
s.update([2, 3, 4, 5, 6])
s

{1, 2, 3, 4, 5, 6}

In [6]:
s.remove(4) # Element not will raise error

In [7]:
s.discard(3)

In [8]:
s1 = {1, 2, 3}
s2 = {3, 4, 5}
s1.union(s2)  # or 's1 | s2'

{1, 2, 3, 4, 5}

In [12]:
s1 = {1, 2, 3}
s2 = {2, 3, 4}
s3 = {3, 4, 5}
s1.intersection(s2, s3)  # or 's1 & s2 & s3'

{3}

In [13]:
s1 = {1, 2, 3}
s2 = {2, 3, 4}
s1.symmetric_difference(s2) 

{1, 4}

In [15]:
import operator
data = [1, 2, 3, 4, 5]
result = itertools.accumulate(data, operator.sub)
for each in result:
    print(each)

1
-1
-4
-8
-13


In [12]:
data = [5, 2, 6, 4, 5, 9, 1]
result = itertools.accumulate(data)
for each in result:
    print(each)

5
7
13
17
22
31
32


In [13]:
'Hello'.rjust(10,'*')

'*****Hello'

In [14]:
'Hello'.ljust(10,'-')

'Hello-----'

In [15]:
'Hello'.center(20, '=')

'=======Hello========'

In [16]:
import re
phone_num_regex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
mo = phone_num_regex.search('My number is 415-555-4242.')
print('Phone number found: {}'.format(mo.group()))

Phone number found: 415-555-4242


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [5]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [6]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [9]:
a=9
r=5
count=[]
for i in range(1,r):
    count.append(int('%s'%a*i))
print(count)
print(sum(count))

[9, 99, 999, 9999]
11106


In [23]:
print ("My name is %s and weight is %d kg!" % ('Zara', 21))

My name is Zara and weight is 21 kg!


In [26]:
from platform import python_version

print(python_version())

3.8.3


In [7]:
ls = [10,30,20]
sum(ls)

60

In [11]:
import numpy as np

In [16]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.random.randn(5,1)

array([[ 2.01051748],
       [-1.32324331],
       [ 0.85703659],
       [ 0.559558  ],
       [ 0.62421815]])

In [26]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))


Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


In [30]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))


Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [31]:
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))


Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [46]:
import numpy as np
X = np.array([(1, 7, 13, 15)])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))


Original array:
[[ 1  7 13 15]]
Size of the memory occupied by the said array:
32 bytes


In [3]:
conda update --all

Solving environment: \ 
  - defaults/linux-64::docutils-0.17-py38h06a4308_1, defaults/noarch::decorator-5.0.6-pyhd3eb1b0_0, defaults/noarch::networkx-2.5-py_0, defaults/noarch::sphinx-3.4.3-pyhd3eb1b0_0
  - defaults/linux-64::docutils-0.17-py38h06a4308_1, defaults/noarch::decorator-4.4.2-pyhd3eb1b0_0, defaults/noarch::networkx-2.5.1-pyhd3eb1b0_0, defaults/noarch::sphinx-3.4.3-pyhd3eb1b0_0
  - defaults/linux-64::docutils-0.16-py38_1, defaults/noarch::decorator-4.4.2-pyhd3eb1b0_0, defaults/noarch::networkx-2.5.1-pyhd3eb1b0_0, defaults/noarch::sphinx-3.5.4-pyhd3eb1b0_0
  - defaults/linux-64::docutils-0.16-py38_1, defaults/noarch::decorator-5.0.6-pyhd3eb1b0_0, defaults/noarch::networkx-2.5-py_0, defaults/noarch::sphinx-3.5.4-pyhd3eb1b0done

## Package Plan ##

  environment location: /home/vijay/anaconda3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    absl-py-0.12.0             |   py38h0

nettle-3.7.2         | 811 KB    | ##################################### | 100% 
cython-0.29.23       | 2.0 MB    | ##################################### | 100% 
libedit-3.1.20210216 | 167 KB    | ##################################### | 100% 
google-auth-oauthlib | 18 KB     | ##################################### | 100% 
nbclassic-0.2.6      | 19 KB     | ##################################### | 100% 
ca-certificates-2021 | 114 KB    | ##################################### | 100% 
libidn2-2.3.0        | 86 KB     | ##################################### | 100% 
zeromq-4.3.4         | 331 KB    | ##################################### | 100% 
intel-openmp-2021.2. | 1.3 MB    | ##################################### | 100% 
pyspark-3.1.1        | 194.1 MB  | ##################################### | 100% 
jupyter_server-1.4.1 | 317 KB    | ##################################### | 100% 
gettext-0.21.0       | 2.6 MB    | ##################################### | 100% 
prompt_toolkit-3.0.1 | 12 KB

secretstorage-3.3.1  | 24 KB     | ##################################### | 100% 
soupsieve-2.2.1      | 32 KB     | ##################################### | 100% 
anyio-2.2.0          | 125 KB    | ##################################### | 100% 
isort-5.8.0          | 81 KB     | ##################################### | 100% 
ipython-7.22.0       | 982 KB    | ##################################### | 100% 
grpcio-1.36.1        | 1.9 MB    | ##################################### | 100% 
mkl_fft-1.3.0        | 177 KB    | ##################################### | 100% 
wurlitzer-2.1.0      | 14 KB     | ##################################### | 100% 
autopep8-1.5.6       | 43 KB     | ##################################### | 100% 
keyring-22.3.0       | 53 KB     | ##################################### | 100% 
dask-2021.4.0        | 5 KB      | ##################################### | 100% 
tqdm-4.59.0          | 93 KB     | ##################################### | 100% 
openpyxl-3.0.7       | 159 K