In [1]:
import numpy as np

In [2]:
# Write a Python program to print the NumPy version in your system
np.version.version

'1.19.2'

In [3]:
# Write a Python program to reverse an array 
arr = np.array([1,2,5,4,9,7,8,6,3])
arr[::-1]

array([3, 6, 8, 7, 9, 4, 5, 2, 1])

In [4]:
# Write a Python program to convert a list and tuple into arrays.
arr1 = np.array((1, 2, 3, 4, 5))
arr1

array([1, 2, 3, 4, 5])

In [5]:
# Write a Python program to find common values between two arrays.
a = np.array([2,5,6,4,7])
b = np.array([7,4,8,9,2])


In [6]:
np.intersect1d(a,b)

array([2, 4, 7])

In [7]:
#  Write a Python program compare two arrays using numpy.
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))

[False  True False False  True]
[False  True False False  True]
[ True False  True  True False]


In [10]:
# Write a Python program to change the dimension of an array
aa = np.arange(10)
aa.reshape(5,-1)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
n = np.arange(1,100)
ai = n[(n%3==0) | (n%5==0)]
print(ai)
ai.sum()

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


2318

In [10]:
# Write a Python program to convert a NumPy array into Python list structure.
an = np.array([3,4,6,8,5])
list(an)

[3, 4, 6, 8, 5]

In [11]:
# Write a Python program to how to add an extra column to a numpy array.
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[10], [20]])
np.append(x,y,axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [12]:
# Write a Python program to check whether the numpy array is empty or not
a = np.array([])
print(a.size==0)

True


In [13]:
# Write a Python program to normalize a 3x3 random matrix
x=np.random.randint(9,size=(3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[8 8 2]
 [2 0 2]
 [0 5 0]]
After normalization:
[[1.    1.    0.25 ]
 [0.25  0.    0.25 ]
 [0.    0.625 0.   ]]


In [14]:
# How to ignore all numpy warnings (not recommended)
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [15]:
# How to swap two rows of an array?
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(a)
print('--'*10)
a[[0, 1]] = a[[1, 0]]
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
--------------------
[[5 7 0]
 [4 3 1]
 [9 9 3]
 [8 2 4]]


In [5]:
# Compute bootstrapped 95% confidence
# intervals for the mean of a 1D array X (i.e.,
# resample the elements of an array with
# replacement N times, compute the mean of
# each sample, and then compute percentiles
# over the means).
X= np.random.randn(100)
N=1000
idx = np.random.randint(0,X.size,(N,X.size))
idx

means = X[idx].mean(axis=1)
per = np.percentile(means,[2.5,97.5])
per


array([-0.37392105,  0.06131671])

In [17]:
# Python program to create a random vector of size 10 and sort it.
ranV = np.array(np.random.random(10))
print('Random vector ')
print(ranV)
print('Sorted Random vector ')
ranV.sort()
print(ranV)

Random vector 
[0.16194178 0.67993243 0.42583368 0.48150485 0.90299704 0.30504186
 0.20608411 0.3335155  0.34167075 0.65984491]
Sorted Random vector 
[0.16194178 0.20608411 0.30504186 0.3335155  0.34167075 0.42583368
 0.48150485 0.65984491 0.67993243 0.90299704]


In [18]:
# Write a Python program to check two random arrays are equal or not.
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 0 0 1 0]
Second array:
[1 1 1 0 1 1]
Test above two arrays are equal or not!
False


In [12]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise
x1 = np.random.randint(5, size=6)
x2 = np.random.randint(5, size=6)

print(x1)
print(x2)
print(np.add(x1, x2))
print(np.subtract(x1, x2))
print(np.multiply(x1, x2))
print(np.divide(x1, x2))

[1 1 4 1 3 1]
[3 3 0 0 3 4]
[4 4 4 1 6 5]
[-2 -2  4  1  0 -3]
[3 3 0 0 9 4]
[0.33333333 0.33333333        inf        inf 1.         0.25      ]


<ipython-input-12-690182bf2caf>:10: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(x1, x2))


In [14]:
# Write a Python program to get the dates of yesterday, today and tomorrow.
today = np.datetime64('today','D')
print('TODAY ',(today))
tomorrow = np.datetime64('today','D')+np.timedelta64('1','D')
print('TOMORROW ' ,(tomorrow))
yesterd = np.datetime64('today','D')-np.timedelta64('1','D')
print('TODAY ',(yesterd))

TODAY  2021-05-09
TOMORROW  2021-05-10
TODAY  2021-05-08
