## Decision Trees
### Agenda
1. Introduction to Decision Trees
2. The Decision Tree Algorithms
3. Decision Tree for Classification
4. Decision Tree for Regression
5. Advantages & Limitations of Decision Trees

### 1. Introduction to Decision Trees
```
* Non-parametric supervised learning method for regression & classification
* It's similar to playing 'dumb charades'.
* A good algorithm will have less & right questions compared to not-so-good one
* The nodes are questions & leafs are prediction
```


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

In [3]:
! ls

sample_data


In [4]:
play_data = pd.read_csv('tennis.csv.txt')

FileNotFoundError: ignored

In [ ]:
play_data

* A decision tree for above data

<img src="https://github.com/awantik/machine-learning-slides/blob/master/dt4.PNG?raw=true" width="600px">

### 2. Decision Tree Algorithm

* Decision Tree is based on (CART) which is advancement of ID3, developed in 1986 by Ross Quinlan.
* ID3 works when feature data & target data both are categorical in nature
* C4.5 is an advancement of ID3, it coverts continous features into categorical features. Then, proceeds with ID3
* CART is based on C4.5, with slight advancement of 'target can be continous'.
* scikit-learn decision trees are based on CART

#### Criterion of creating Decision Tree
* Entropy - Objective of CART is to maximize information gain in each split
* Gini Impurity - If classes are mixed, gini impurity is maximul
##### Both the approaches, yields almost same results. We will discuss algorithm using Entropy


### Entropy of play
* Entropy(play) = – p(Yes) . log2p(Yes) – p(No) . log2p(No)

In [ ]:
play_data.play.value_counts()

In [ ]:
Entropy_Play = -(9/14)*np.log2(9/14) -(5/14)*np.log2(5/14)

In [ ]:
Entropy_Play

### Information Gain
* The information gain is based on the decrease in entropy after a dataset is split on an attribute. 
* Constructing a decision tree is all about finding attribute that returns the highest information gain (i.e., the most homogeneous branches).
* Gain(S, A) = Entropy(S) – ∑ [ p(S|A) . Entropy(S|A) ]
* We intend to choose the attribute, splitting by which information gain will be the most
* Next step is calculating information gain for all attributes

#### Information Gain on splitting by Outlook
* Gain(Play, Outlook) = Entropy(Play) – ∑ [ p(Play|Outlook) . Entropy(Play|Outlook) ]
* Gain(Play, Outlook) = Entropy(Play) – [ p(Play|Outlook=Sunny) . Entropy(Play|Outlook=Sunny) ] – [ p(Play|Outlook=Overcast) . Entropy(Play|Outlook=Overcast) ]  – [ p(Play|Outlook=Rain) . Entropy(Play|Outlook=Rain) ] 

In [ ]:
play_data[play_data.outlook == 'sunny']

In [ ]:
# Entropy(Play|Outlook=Sunny)
Entropy_Play_Outlook_Sunny =-(3/5)*np.log2(3/5) -(2/5)*np.log2(2/5)

In [ ]:
Entropy_Play_Outlook_Sunny

In [ ]:
play_data[play_data.outlook == 'overcast']

In [ ]:
# Entropy(Play|Outlook=overcast)
# Since, it's a homogenous data entropy will be 0

In [ ]:
play_data[play_data.outlook == 'rainy']

In [ ]:
# Entropy(Play|Outlook=rainy)
Entropy_Play_Outlook_Rain = -(2/5)*np.log2(2/5) - (3/5)*np.log2(3/5)

In [ ]:
Entropy_Play_Outlook_Rain

#### Gain on splitting by attribute outlook

In [ ]:
#Gain(Play, Outlook) = Entropy(Play) – [ p(Play|Outlook=Sunny) . Entropy(Play|Outlook=Sunny) ] – 
#[ p(Play|Outlook=Overcast) . Entropy(Play|Outlook=Overcast) ] – [ p(Play|Outlook=Rain) . Entropy(Play|Outlook=Rain) ]

Entropy_Play - (5/14)*Entropy_Play_Outlook_Sunny - (4/14)*0 - (5/14) * Entropy_Play_Outlook_Rain 

#### Other gains
* Gain(Play, Temperature) - 0.029
* Gain(Play, Humidity) - 0.151
* Gain(Play, Wind) - 0.048

#### Conclusion - Outlook is winner & thus becomes root of the tree
<img src="https://i1.wp.com/sefiks.com/wp-content/uploads/2017/11/tree-v1.png?zoom=1.25&resize=728%2C252&ssl=1" width="600px">

### Time to find the next splitting criteria

In [ ]:
play_data[play_data.outlook == 'overcast']

##### Conclusion - If outlook is overcast, play is true

### Let's find the next splitting feature

In [ ]:
play_data[play_data.outlook == 'sunny']

In [ ]:
# Entropy(Play_Sunny|)
Entropy_Play_Outlook_Sunny =-(3/5)*np.log2(3/5) -(2/5)*np.log2(2/5)

In [ ]:
Entropy_Play_Outlook_Sunny

### Information Gain for humidity

In [ ]:
#Entropy for attribute high = 0, also entropy for attribute normal = 0 
Entropy_Play_Outlook_Sunny - (3/5)*0 - (2/5)*0

### Information Gain for windy
* False -> 3 -> [1+ 2-]
* True -> 2 -> [1+ 1-]

In [ ]:
Entropy_Wind_False = -(1/3)*np.log2(1/3) - (2/3)*np.log2(2/3)

In [ ]:
Entropy_Wind_False

In [ ]:
Entropy_Play_Outlook_Sunny - (3/5)* Entropy_Wind_False  - (2/5)*1 

### Information Gain for temperature
* hot -> 2 -> [2- 0+]
* mild -> 2 -> [1+ 1-]
* cool -> 1  -> [1+ 0-]

In [ ]:
Entropy_Play_Outlook_Sunny - (2/5)*0 - (1/5)*0 - (2/5)* 1

#### Conclusion : Humidity is the best choice on sunny branch

<img src="https://github.com/awantik/machine-learning-slides/blob/master/dt3.PNG?raw=true" width="600px">

In [ ]:
play_data[(play_data.outlook == 'sunny') & (play_data.humidity == 'high')]

In [ ]:
play_data[(play_data.outlook == 'sunny') & (play_data.humidity == 'normal')]

### Splitting the rainy branch

In [ ]:
play_data[play_data.outlook == 'rainy']

In [ ]:
# Entropy(Play_Rainy|)
Entropy_Play_Outlook_Rainy =-(3/5)*np.log2(3/5) -(2/5)*np.log2(2/5)

In [ ]:
Entropy_Play_Outlook_Rainy

### Information Gain for temp
* mild -> 3 [2+ 1-]
* cool -> 2 [1+ 1-]

In [ ]:
Entropy_Play_Outlook_Rainy - (3/5)*0.918 - (2/5)*1

### Information Gain for Windy

In [ ]:
Entropy_Play_Outlook_Rainy - (2/5)*0 - (3/5)*0

### Information Gain for Humidity
* High -> 2 -> [1+ 1-]
* Normal -> 3 -> [2+ 1-]

In [ ]:
Entropy_Play_Outlook_Rainy_Normal = -(1/3)*np.log2(1/3) - (2/3)*np.log2(2/3)

In [ ]:
Entropy_Play_Outlook_Rainy_Normal

In [ ]:
Entropy_Play_Outlook_Rainy - (2/5)*1 - (3/5)*Entropy_Play_Outlook_Rainy_Normal

### Final Tree

<img src="https://github.com/awantik/machine-learning-slides/blob/master/dt4.PNG?raw=true" width="600px">

### 3. Decision Tree for Classification
* The leaf nodes of decision tree decides the class
* CART will convert features with continues values into categorical values
* Different tree will be generated with same data given in different order

In [5]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, export_graphviz, ExtraTreeClassifier

In [6]:
iris = load_iris()

In [7]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [8]:
iris.target[:5]

array([0, 0, 0, 0, 0])

In [31]:
dt = DecisionTreeClassifier(criterion='entropy', random_state=5)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
trainX,testX,trainY,testY = train_test_split(iris.data, iris.target)

In [43]:
dt.fit(trainX,trainY)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=5, splitter='best')

In [44]:
dt.score(trainX, trainY)

1.0

In [45]:
dt.score(testX,testY)

0.9210526315789473

In [ ]:
export_graphviz(dt,'dt.tree')

### Visualizing the tree
*https://graphviz.org/

* Criteria - Entropy
<img src="https://github.com/awantik/machine-learning-slides/blob/master/dt6.PNG?raw=true">

In [46]:
dt.predict(testX)

array([2, 1, 2, 2, 0, 1, 2, 2, 2, 0, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 0,
       2, 0, 1, 1, 1, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 2])

#### Feature Importances
* Important features will be higher up the tree
* We can use this techniques to identify important features

In [47]:
dt.feature_importances_

array([0.01552697, 0.        , 0.31096264, 0.67351039])

#### Visualizing Decision Tree Decision Boundry

In [ ]:
from sklearn.datasets import make_blobs

In [ ]:
X,Y = make_blobs(n_features=2, n_samples=1000, cluster_std=.8, centers=4, random_state=6)

In [ ]:
plt.scatter(X[:,0],X[:,1],c=Y,s=5, cmap='viridis')

In [ ]:
dt = DecisionTreeClassifier()

In [ ]:
dt.fit(X,Y)

In [ ]:
plot_step = 0.2
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, plot_step),
                         np.arange(y_min, y_max, plot_step))

In [ ]:
outcome = dt.predict(np.c_[xx.ravel(), yy.ravel()])

In [ ]:
xx.shape

In [ ]:
plt.scatter(X[:,0],X[:,1],c=Y,s=5,cmap='viridis')
plt.scatter(xx.ravel(),yy.ravel(),c=outcome,s=1,alpha=1, cmap='viridis')
plt.show()

### 4. Decision Tree for Regression
* Continues target is predicted with Tree.
* ID3 is modified for regression by replacing Information Gain with Mean Squared Error.
* Decision Tree tries to partition data into subsets of homogenous contents ( minimize mean squared error )

In [ ]:
play_time = pd.read_csv('data/tennis-time.csv.txt')

In [ ]:
play_time

In [ ]:
from sklearn.preprocessing import LabelEncoder
for col in ['outlook','temp','humidity','windy']:
    le = LabelEncoder()
    play_time[col] = le.fit_transform(play_time[col])

In [ ]:
print (play_time)

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
dt = DecisionTreeRegressor()

In [ ]:
dt.fit(play_time.drop('time',axis=1), play_time.time)

In [ ]:
export_graphviz(dt,'regtree.dot',feature_names=['outlook','temp','humidity','windy'])

In [ ]:
play_time

<img src="https://github.com/awantik/machine-learning-slides/blob/master/dt8.PNG?raw=true">

In [ ]:
dt.predict([[2,2,1,1]])

In [ ]:
dt.feature_importances_

### 5. Advantages of Decision Tree
* Highly Interpretable & can be visualized
* Minimal data preprocessing - missing data handling, normalizing, one-hot-encoding not required
* Handle both neumerical & categorical values
* Supports multi-output 

#### Understanding Multi-Output Problem
* Supervised learning problem with multiple outputs, target is 2D
* If there is no correlation between target, they can be independently calculated using N models ( in case of N targets )
* Since predictors are same, outputs are likely to be correlated.
* Like many other models, decision trees allows for multi-output targets

### 6. Limitations of Decision Tree
* Overfitting - height of tree kept growing with addition of more data
* Slight changes in data or order of data can change the tree
* Imbalanced classes datasets creates biased tree so data needs balancing

##### The above two limitations are handled by ensemble methods

#### Pruning
* A technique of machine learning which reduces height of the tree by chopping off parts of the tree that's not doing anything significant in prediction
* Two types of pruning - Prepruning & Postpruning
  - Prepruning : Don't allow tree to grow beyond this point
  - Postpruning : Allows tree to grow as much as possible, then prune the tree

* Post Pruning is not currently supported in scikit
* This can be achieved using min_samples_leaf & max_depth

![](img/questions-01.png)

# 1. Conceptual Questions 

1. Calculate the self entropy of the following coin with bias :  
  a. p=0.5  
  b. p=0.9  
  c. p=1  
  
2. Calculate the cross entropy of the dice with bias=\[ 0.1, 0.2, 0.1, 0.15, 0.15, 0.3 \] in the following cases  :  
  a. output=1  
  b. output=2  
  c. output=6  
  
3. Tell the cases where you think that cross entropy would be higher for a coin.  
  a. p(H)=0.9, outcome=Head  
  b. p(H)=0.1, outcome=Tail  
  c. p(H)=0.99, outcome=Tail  
  
4. What is Information Gain in terms of Entropy? In case of predicting the number of wickets, what would be information gain on knowledge of weather? 
  
5. What is Gini's Impurity? Why do we use it more often in popular Decision Tree algorithms like CART, rather then entropy? What does the formula signify?
  
6. If the size of feature vector for data point is 5, what will be the depth of the tree?  
  
7. What is the disadvantage of having a tree branched over all the features ? How do we control/prun the growth of tree?  

8. Why is there an aversion in the ML community for using decision tree as a primary choice for building a classifier? 

9. Think about the advantages/Disadvantages of Decision Tree vs Linear Regression.

# 2. Programming Questions 
1. Build a decision Tree Classifier from scratch in Python, Choose the features based on Information Gain
2. Plot self entropy and Gini's Impurity against the bias in case of coin tossing experiment
3. Try to use Decision Tree Classifier to find out if the person will get high, medium or low salary based on the rest of the features. The data is given bellow. Visualize the same using graphViz

In [ ]:
adult_data = pd.read_csv('adult.data.txt', names=cols)